export const nutrientLabels = [
    "Apple-->Apple_scab-->cobalt",
    "Apple-->Black_rot-->nitrogen",
    "Apple-->Cedar_apple_rust-->manganese",
    "Apple-->healthy",
    "Blueberry-->healthy",
    "Cherry_(including_sour)-->calcium",
    "Cherry_(including_sour)-->healthy",
    "Corn_(maize)-->Cercospora_leaf_spot Gray_leaf_spot --> iron",
    "Corn_(maize)-->Common_rust_ --> Phosphorus",
    "Corn_(maize)-->Northern_Leaf_Blight --> Manganese",
    "Corn_(maize)-->healthy",
    "Grape-->Black_rot-->Nitrogen",  
    "Grape--> Esca_(Black_Measles --> Phosphorous",
    "Grape--> Isariopsis_Leaf_Spot --> Magnesium" ,
    "Grape-->healthy",
    "Orange-->Haunglongbing_(Citrus_greening)--> Potassium",
    "Peach-->Bacterial_spot-->Copper",
    "Peach-->healthy",
    "Pepper,_bell-->Bacterial_spot-->Copper",
    "Pepper,_bell-->healthy",
    "Potato-->Early_blight-->phosphorus",
    "Potato-->Late_blight-->calcium",
    "Potato-->healthy",
    "Raspberry-->healthy",
    "Soybean-->healthy",
    "Squash-->Powdery_mildew-->calcium",
    "Strawberry-->Leaf_scorch-->Molybdenum",
    "Strawberry-->healthy",
    "Tomato-->Bacterial_spot-->Copper",
    "Tomato-->Early_blight-->Phosphorus",
    "Tomato-->Late_blight-->calcium",
    "Tomato-->Leaf_Mold-->Nitrogen",
    "Tomato-->Septoria_leaf_spot-->Manganese",
    "Tomato-->Spider_mites Two-spotted_spider_mite-->Iron",
    "Tomato-->Target_Spot-->Copper",
    "Tomato-->Tomato_Yellow_Leaf_Curl_Virus-->Nitrogen",
    "Tomato-->Tomato_mosaic_virus-->Manganese",
    "Tomato-->healthy"
]