export const nutrientLabels = [
    "Apple-->Apple_scab-->Cobalt",
    "Apple-->Black_rot-->Nitrogen",
    "Apple-->Cedar_apple_rust-->Manganese",
    "Apple-->healthy",
    "Blueberry-->healthy",
    "Cherry_(including_sour)-->Calcium",
    "Cherry_(including_sour)-->healthy",
    "Corn_(maize)-->Cercospora_leaf_spot Gray_leaf_spot --> Iron",
    "Corn_(maize)-->Common_rust_ --> Phosphorus",
    "Corn_(maize)-->Northern_Leaf_Blight --> Manganese",
    "Corn_(maize)-->healthy",
    "Grape-->Black_rot-->Nitrogen",  
    "Grape--> Esca_(Black_Measles --> Phosphorous",
    "Grape--> Isariopsis_Leaf_Spot --> Magnesium" ,
    "Grape-->healthy",
    "Orange-->Haunglongbing_(Citrus_greening)--> Potassium",
    "Peach-->Bacterial_spot-->Copper",
    "Peach-->healthy",
    "Pepper,_bell-->Bacterial_spot-->Copper",
    "Pepper,_bell-->healthy",
    "Potato-->Early_blight-->Phosphorus",
    "Potato-->Late_blight-->Calcium",
    "Potato-->healthy",
    "Raspberry-->healthy",
    "Soybean-->healthy",
    "Squash-->Powdery_mildew-->Calcium",
    "Strawberry-->Leaf_scorch-->Molybdenum",
    "Strawberry-->healthy",
    "Tomato-->Bacterial_spot-->Copper",
    "Tomato-->Early_blight-->Phosphorus",
    "Tomato-->Late_blight-->Calcium",
    "Tomato-->Leaf_Mold-->Nitrogen",
    "Tomato-->Septoria_leaf_spot-->Manganese",
    "Tomato-->Spider_mites Two-spotted_spider_mite-->Iron",
    "Tomato-->Target_Spot-->Copper",
    "Tomato-->Tomato_Yellow_Leaf_Curl_Virus-->Nitrogen",
    "Tomato-->Tomato_mosaic_virus-->Manganese",
    "Tomato-->healthy"
]


export const oMeasures = {
    'Calcium' : ['Add some eggshells to your soil.','Use soil additives to enhance its Calcium content','Add epsom salts to your plants.'],
    'Manganese' : ['Manganese deficiency is controlled by using Manganese sulphate (MnSO4 .7H2O) as a soil applicant or a foliage spray. '],
    'Nitrogen' : ['Adding compost manure to the soil','planting green manure crop such as borge','adding coffee grounds to the soil'],
    'Copper' : ['Copper deficiency due to high soil pH should be treated by lowering soil pH with acidifiers such as sulfur or ammonium sulfate.'],
    'Iron' : ['Reducile Phosphorus in Soil'],
    'Cobalt' : ['Manure from animals that received adequate dietary','Kelp-based fertilizers are also useful.'],
    'Potassium' : ['feeding with home-made comfrey liquid, adding seaweed meal, vermiculite, composted bracken, and compost rich in decayed banana peels.'],
    'Molybdenum' : ['Alkaline soils have more available Molybdenum than acidic soils and it is easier for plants to uptake.'],
    'Magnesium' : ['A foliar feed fertilizer with Manganese will help to alleviate the issue.'],
    'Phosphorus': ['a fast acting source that is made from ground animal bones which is rich in phosphorous.','a slower acting source where the soil needs to convert the rock phosphate into phosphorous that the plants can use.']
}